#!/usr/bin/env bash

if [ -n "$(lsb_release -sir| grep blackPanther)" ];then
    SUDO=
else
    SUDO=sudo
fi

user=$USER

if [ "$#" == 1 ]; then
	user=$1
fi

proc="0"

for pid in $(pidof hl2_linux)
do
	if [ -n "$SUDO" ];then
	    CMD="sudo -H -u $user kill -0 $pid"
	else
	    CMD="su -c \"kill -0 $pid\"  $user"
	fi
	if $CMD
	then
		proc=$pid
		break
	fi
done


if [ "$proc" == "0" ]
then
	echo "TF2 for $user is not running"
	continue
fi

echo Attaching to "$proc"

FILENAME=$(realpath "bin/libcathook.so")

echo loading "$FILENAME" to "$proc"

$SUDO killall -19 steam
$SUDO killall -19 steamwebhelper

$SUDO gdb -n -q -batch \
  -ex "attach $proc" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$FILENAME\", 1)" \
  -ex "call dlerror()" \
  -ex 'print (char *) $2' \
  -ex "detach" \
  -ex "quit"

$SUDO killall -18 steamwebhelper
$SUDO killall -18 steam
