#!/usr/bin/env bash

DEST=$1

if ! [ -d "$DEST" ]; then
    echo "Creating cathook data directory at $DEST"
    if [ -n "$(lsb_release -sir | grep blackPanther)" ];then
	# do not apply 777 on blackPanther ! this is insecure
	su -c "mkdir -p $DEST && chown $USER:$USER $DEST"
    else
	sudo mkdir -p "$DEST"
	sudo chown -R $USER "$DEST"
	sudo chmod -R 777 "$DEST"
    fi
fi

rsync -avh --progress "data/" "$DEST"
